Add pre_commit hook and check flutter format in pre_push

diff --git a/pre_push b/pre_push
--- a/pre_push
+++ b/pre_push
@@ -1,6 +1,13 @@
 #!/bin/sh
 # executed from `.git/hooks/`
 
+flutter format --set-exit-if-changed .
+
+if [[ $? -ne 0 ]]; then
+        echo "--- format failed"
+        exit 1
+fi
+
 flutter analyze
 
 if [[ $? -ne 0 ]]; then
